[package]
name = "wincomp"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = { version = "0.6", features = ["simd"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false
